# Generated by Django 4.1 on 2023-03-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.DecimalField(decimal_places=1, max_digits=3)),
                ('profession', models.CharField(max_length=40)),
                ('sal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
