# Generated by Django 4.1 on 2023-04-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_alter_user_age_alter_user_sal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='sal',
            field=models.IntegerField(),
        ),
    ]
